spring.application.name=person

server.port=8080

location.service.url=http://localhost:8081
weather.service.url=http://localhost:8082

spring.datasource.url=jdbc:h2:file:./data/persondb
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console