spring.config.activate.on-profile=instance1
server.port=8087
spring.datasource.url=jdbc:h2:file:./data/weatherdb_instance1;DB_CLOSE_ON_EXIT=FALSE
eureka.instance.instance-id=${spring.application.name}:${server.port}