spring.application.name=weather
server.port=8082
spring.cache.caffeine.spec=expireAfterWrite=60s
appid=a3198c00d233c295d46bf68a12d0f2b3
management.endpoints.web.exposure.include=health, caches
management.endpoint.health.show-details=always
management.endpoint.caches.enabled=true
logging.level.org.springframework.web=DEBUG
logging.level.com.example.location=DEBUG